### ISSUE TITLE
Unexpected server response: 307

### ISSUE THREAD

**Issue by eja0iq** [KagChi/lavalink-repl#1]
Im getting that error after i use lavalink from repl.it once and then if i restart the bot it cant connect to the lavalink with error Unexpected server response: 307 but there is no error from lavalink

**Comment by KagChi** [comment]
dev build need to change ws connection from ws to wss, and rest from http to https i suggest to use modified lavalink client

**Comment by eja0iq** [comment]
Where i can find it?

**Comment by KagChi** [comment]
i have modified shoukaku, or you can use erela.js from github master

**Comment by eja0iq** [comment]
Thanks this really helpful
