### ISSUE TITLE
Unexpected server response: 400

### ISSUE THREAD

**Issue by SuperSweatyTejas** [KagChi/lavalink-repl#12]
**What client do you use?**
Using erela.js
**Are you sure using secure options?**
N/A
**Are you sure using port 443 when connecting?**
Yes

receiving ``Unexpected server response: 400``

Port:443

Host/Id: lavalink-repl.username.repl.co

Pass: from application.yml file

**Comment by KagChi** [comment]
> Are you sure using secure options?
N/A

You're not using secure option.
