### ISSUE TITLE
[CANNOT CONNECT in Lavalink]

### ISSUE THREAD

**Issue by anthonyjohnhinay** [KagChi/lavalink-repl#17]
**What client do you use?**
Lavalink 
**Are you sure using secure options?**
Nope
**Are you sure using port 443 when connecting?**
Yes
Hello im trying to connect the lavalink into my bot but seems it says that the remote sever return 400
[NODE-eu-lavalink-repl.vnns.repl.co:443] The remote server returned code 400, the expected code was 101. This usually indicates that the remote server is a webserver and not Lavalink. Check your ports, and try again.

**Comment by KagChi** [comment]
enable the secure option if you client have that

**Comment by KagChi** [comment]
otherwise i cant help

**Comment by anthonyjohnhinay** [comment]
Hello im using lavalink module by devoxin (https://github.com/Devoxin/Lavalink.py)

How do you add the secure option on this? Byw thanks for answering


``class Music(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

        if not hasattr(bot, 'lavalink'):  # This ensures the client isn't overwritten during cog reloads.
            bot.lavalink = lavalink.Client(bot.user.id)
            bot.lavalink.add_node('127.0.0.1', 2333, 'youshallnotpass', 'eu', 'default-node')  # Host, Port, Password, Region, Name

        `lavalink.add_event_hook(self.track_hook)
```

**Comment by KagChi** [comment]
ask the maintainer not me

**Comment by KagChi** [comment]
looks like lavalink.py doesnt have secure option, might want to move wavelink instead? i see they have the option

**Comment by anthonyjohnhinay** [comment]
I figured out, by setting the bot to localhost inside the repl.it you can actually host it together with Lavalink server
