### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by binary-blazer** [KagChi/lavalink-repl#18]
How can i fix this error??
![Firefox_Screenshot_2022-02-20T11-39-04 385Z](https://user-images.githubusercontent.com/81481526/154840681-04cbe7c8-0299-437f-bf73-d1136c3aff51.png)

**Comment by JanjyTapYT** [comment]
pls help

**Comment by JanjyTapYT** [comment]
and btw uptimerobot isnt working too. the project is down

**Comment by noxzym** [comment]
> How can i fix this error?? ![Firefox_Screenshot_2022-02-20T11-39-04 385Z](https://user-images.githubusercontent.com/81481526/154840681-04cbe7c8-0299-437f-bf73-d1136c3aff51.png)

did your bot can connect to your lavalink? if yes, just ignore that error.

**Comment by JanjyTapYT** [comment]
my bot can connect to lavalink servers but not to mine

**Comment by noxzym** [comment]
> no my bot isnt connecting

check your lavalink config and make sure your password is correct (required `secure: true`)
