### ISSUE TITLE
Cannot connect error 176. 

### ISSUE THREAD

**Issue by teheim** [KagChi/lavalink-repl#19]
**What client do you use?**
Glitch, 
**Are you sure using secure options?**
Yes 
**Are you sure using port 443 when connecting?**
Yes

The bot has worked like normal for months. But today it stopped working with error 176

![image](https://user-images.githubusercontent.com/42135879/156422542-a9789975-db27-4667-8cf7-e1b30304aa1e.png)

**Comment by KagChi** [comment]
*Glitch* are not valid client.

**Comment by teheim** [comment]
Well i am using glitch for the bot BUT this Repo i am using in Replit

**Comment by KagChi** [comment]
either replit or glitch is still not valid client, and please ignore about authorization failed.

**Comment by KagChi** [comment]
you should brush up your knowledge about lavalink.
