### ISSUE TITLE
lavalink is not working could please help me 

### ISSUE THREAD

**Issue by rajamoulimallareddy** [KagChi/lavalink-repl#2]
I did what u said in the readme file but still its not working please help me.

**Comment by KagChi** [comment]
what issue do you had?

**Comment by KagChi** [comment]
sorry for late reply anyway

**Comment by rajamoulimallareddy** [comment]
i did what u said but its not working node isnt conencted please help

**Comment by KagChi** [comment]
what client you used?

**Comment by rajamoulimallareddy** [comment]
lavacord

**Comment by KagChi** [comment]
lavacord doesnt support secure protocols for now, use another client such as shoukaku or erela.js

**Comment by KagChi** [comment]
https://github.com/KagChi/noteblock you can use this
