### ISSUE TITLE
[CANNOT CONNECT]

### ISSUE THREAD

**Issue by LonelyGuy12** [KagChi/lavalink-repl#21]
**What client do you use?**
wavelink.py
**Are you sure using secure options?**
Yes
**Are you sure using port 443 when connecting?**
Yes!!

```195812001/195812001
Extracting /tmp/jabba-d-181007028 to /home/runner/.jabba/jdk/openjdk@1.13.0-2 
[..................] | rollbackFailedOptional: verb npm-session 4ab7deae[..................] | rollbackFailedOptional: verb npm-session 4ab7deae[..................] | rollbackFailedOptional: verb npm-session 4ab7deae[ .................] | preinstall:lavalink-server: info lifecycle lavali[ .................] | preinstall:lavalink-server: info lifecycle lavali[ .................] / loadIdealTree:loadAllDepsIntoIdealTree: sill inst[  ................] \ loadDep:got: sill install loadAllDepsIntoIdealTre[   ...............] \ loadDep:responselike: sill install loadAllDepsInt[   ...............] \ loadDep:json-buffer: sill install loadAllDepsInto[         .........] | prepare:lavalink-repl: info lifecycle lavalink-se
npm WARN lavalink-server@1.0.0 No repository field.

[         .........] | prepare:lavalink-repl: WARN lavalink-server@1.0.0[         .........] - prepare:lavalink-repl: WARN lavalink-server@1.0.0
audited 33 packages in 1.365s

7 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

[         .........] \ prepare:lavalink-repl: timing audit body Complete

```
It is stuck here when trying to start

**Comment by LonelyGuy12** [comment]
After waiting for an hour now I get this issue
```
2022-04-21 19:10:55.895 ERROR 547 --- [  XNIO-1 task-3] l.server.io.HandshakeInterceptorImpl     : Authentication failed from /172.18.0.1:32788
```

**Comment by KagChi** [comment]
Are you sure wavelink support secure connection? show how you do it.

**Comment by LonelyGuy12** [comment]
> Are you sure wavelink support secure connection? show how you do it.

Yes the node connects properly on regular basis the issue happens randomly at some times and to make sure I don't have code issues I put the node in [this](https://github.com/SudhanPlayz/Discord-MusicBot) and the issue is same

**Comment by LonelyGuy12** [comment]
> Are you sure wavelink support secure connection? show how you do it.

Yes the node connects properly on regular basis the issue happens randomly at some times and to make sure I don't have code issues I put the node in [this](https://github.com/SudhanPlayz/Discord-MusicBot) and the issue is same
