### ISSUE TITLE
Error: Authentication failed :(

### ISSUE THREAD

**Issue by BlackKnight683** [KagChi/lavalink-repl#4]
![image](https://user-images.githubusercontent.com/75422863/118652628-13a76d00-b7e7-11eb-920f-87b270efcd37.png)

**Comment by BlackKnight683** [comment]
thats not my ip... its repl's ip

**Comment by ryuu27** [comment]
have you found any fixes?

**Comment by BlackKnight683** [comment]
nope

**Comment by KagChi** [comment]
please read the readme file.
