### ISSUE TITLE
What is the id and host for the lavalink.

### ISSUE THREAD

**Issue by Madhav-byte-debug** [KagChi/lavalink-repl#5]
I am really sorry. I am dumb. I am a very casual coder and I am new to this. 
```
  Lavalink: {
    id: "",
    host: "",
    port: ,
    pass: "",
  },
```
I understand that the pass will be the pass that i set up in application.yml. and port id 2333
What should be the host and id? like where can i find it in the code or on the console.

**Comment by KagChi** [comment]
read the readme file
