### ISSUE TITLE
Uptimebot

### ISSUE THREAD

**Issue by Tharki-God** [KagChi/lavalink-repl#7]
can you make it so we can actually record its uptime with uptimebot. like maybe add a webpage with express to avoid error code 401 and so that it gets marked as online in uptimebot.

**Comment by KagChi** [comment]
Lavalink already provide webserver, you cant run 2 webserver on 1 replit project, also uptimerobot still work even project returning 401.

**Comment by Tharki-God** [comment]
Well okay but it shows offline in uptomebot even if pinging

**Comment by KagChi** [comment]
uptimerobot will still pinging the project even returning 401, well i used this and still active until now.

**Comment by Tharki-God** [comment]
well i want the status of it as online in uptimebot any workaround?

**Comment by KagChi** [comment]
if you want lavalink response with 200 ok, you have to modify lavalink your self, there no any way.

**Comment by Allvaa** [comment]
> well i want the status of it as online in uptimebot any workaround?

there is a way, you can target it to /version endpoint, which returns 200. but still, you need to set Authorization header to access it, otherwise it will still 401

**Comment by Tharki-God** [comment]
How to set authorization header. Me dumb dumb

**Comment by FatGrizzly** [comment]
![image](https://user-images.githubusercontent.com/66728880/134946346-c97ccbdc-44f0-404a-9e7a-2da63ddcf3a4.png)
edit this to true, and make checks to /metrics endpoint.
It will return 200, no auth required

**Comment by Tharki-God** [comment]
well i chnaged /metrics to /version and let it stay false it still works

**Comment by Tharki-God** [comment]
But still the replit goes offline after some days

**Comment by Moazlion** [comment]
How to make it so it doesn’t turn off after some days?

**Comment by mariathedevofficial** [comment]
I have the same issue bruh, no matter what i try, it will still go offline even after using uptimerobot

**Comment by Tharki-God** [comment]
https://github.com/KagChi/lavalink-railways

**Comment by KagChi** [comment]
Running lavalink on railway is not recommended

**Comment by KagChi** [comment]
they say it's against the TOS, and please don't discuss this further.

**Comment by Tharki-God** [comment]
as you say. and idc about stuff being right so works with me
