### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by gamerspodcast** [KagChi/lavalink-repl#8]
i followed your correctly and i connected the pass,port and link too but when i play some music ,it won't working .. **no nodes are available**

**Comment by KagChi** [comment]
What client do you use?

**Comment by gamerspodcast** [comment]
idk what you asking specifically but i can say that i am using lavalink and
hosting my discord bot on replit

**Comment by KagChi** [comment]
i cant help if you wont fill this form

**What client do you use?**

**Are you sure using secure options?**

**Are you sure using port 443 when connecting?**

**Comment by gamerspodcast** [comment]
discord,js
no
no

**Comment by KagChi** [comment]
Lavalink client bruh

**Comment by KagChi** [comment]
please answer seriously, or this issue will be closed.
