### ISSUE TITLE
cannot connecting nodes

### ISSUE THREAD

**Issue by gamerspodcast** [KagChi/lavalink-repl#9]
pls tell me how to find client

and i am using port 443

 secure: 'true'

i am new to lavalink

**Comment by KagChi** [comment]
do you use any other github repository such as SudhanPlayz/Discord-MusicBot ?, and secure is boolean not string

**Comment by gamerspodcast** [comment]
nope , sorry i mistakenly typed as s string in here, i am using this one :https://github.com/Spiderjockey02/Discord-Bot

**Comment by KagChi** [comment]
where are https://github.com/Spiderjockey02/Discord-Bot bot configuration that has lavalink config to connect?

**Comment by gamerspodcast** [comment]
src/base/audio-manager.js

**Comment by KagChi** [comment]
nodes: [ 
{ host: 'lavalink-repl.yourreplusername.repl.co', port: 443, password: 'youshallnotpass', secure: true },
]

change `yourreplusername` to your repl it username and you should good, dont forgot to run lavalink too

**Comment by gamerspodcast** [comment]
yes its working now, thankyou

**Comment by hezaaheza** [comment]
> do you use any other github repository such as SudhanPlayz/Discord-MusicBot ?, and secure is boolean not string

hello, do you have any idea how to fix this? because i'm using your repo for my lavalink server and its not working on  SudhanPlayz/Discord-MusicBot

**Comment by KagChi** [comment]
on latest SudhanPlayz/Discord-MusicBot commit you can change `secure: true` in botconfig > lavalink config, im sure they provide that option

**Comment by hezaaheza** [comment]
> on latest SudhanPlayz/Discord-MusicBot commit you can change `secure: true` in botconfig > lavalink config, im sure they provide that option

i have done it, but not working, but i got an error.
here my logs.
![image](https://user-images.githubusercontent.com/53120237/133632504-eb626f1f-776e-49d5-a9e6-58bdacef7e82.png)

**Comment by KagChi** [comment]
> > on latest SudhanPlayz/Discord-MusicBot commit you can change `secure: true` in botconfig > lavalink config, im sure they provide that option
> 
> i have done it, but not working, i got an error.
> here my logs.
> ![image](https://user-images.githubusercontent.com/53120237/133632504-eb626f1f-776e-49d5-a9e6-58bdacef7e82.png)

full stackrace please

**Comment by hezaaheza** [comment]
> > > on latest SudhanPlayz/Discord-MusicBot commit you can change `secure: true` in botconfig > lavalink config, im sure they provide that option
> > 
> > 
> > i have done it, but not working, i got an error.
> > here my logs.
> > ![image](https://user-images.githubusercontent.com/53120237/133632504-eb626f1f-776e-49d5-a9e6-58bdacef7e82.png)
> 
> full stackrace please

![image](https://user-images.githubusercontent.com/53120237/133633424-873b48ad-946e-49cf-b6b9-e3cecd739822.png)
here

**Comment by KagChi** [comment]
> > > > on latest SudhanPlayz/Discord-MusicBot commit you can change `secure: true` in botconfig > lavalink config, im sure they provide that option
> > > 
> > > 
> > > i have done it, but not working, i got an error.
> > > here my logs.
> > > ![image](https://user-images.githubusercontent.com/53120237/133632504-eb626f1f-776e-49d5-a9e6-58bdacef7e82.png)
> > 
> > 
> > full stackrace please
> 
> ![image](https://user-images.githubusercontent.com/53120237/133633424-873b48ad-946e-49cf-b6b9-e3cecd739822.png)
> here

try change port to 80 and secure false

**Comment by hezaaheza** [comment]
> > > > > on latest SudhanPlayz/Discord-MusicBot commit you can change `secure: true` in botconfig > lavalink config, im sure they provide that option
> > > > 
> > > > 
> > > > i have done it, but not working, i got an error.
> > > > here my logs.
> > > > ![image](https://user-images.githubusercontent.com/53120237/133632504-eb626f1f-776e-49d5-a9e6-58bdacef7e82.png)
> > > 
> > > 
> > > full stackrace please
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/53120237/133633424-873b48ad-946e-49cf-b6b9-e3cecd739822.png)
> > here
> 
> try change port to 80 and secure false

and i got this
![image](https://user-images.githubusercontent.com/53120237/133634691-b53bf2ee-831f-42c7-9d0f-972f11c69bf6.png)

**Comment by hezaaheza** [comment]
and btw, here my lavalink config for my bot 
![image](https://user-images.githubusercontent.com/53120237/133635063-f92d1434-9f92-4485-bc3e-27d91f66c57c.png)

**Comment by KagChi** [comment]
looks like replit having issue with ssl, wait few days until replit resolves this

**Comment by hezaaheza** [comment]
> looks like replit having issue with ssl, wait few days until replit resolves this

but i'm trying to using my lavalink server in your noteblock and its work..
btw, thanks for your answer.. maybe i'll wait untill they ssl issue. thank you very much

**Comment by ririko5834** [comment]
I have same problem with https://github.com/SudhanPlayz/Discord-MusicBot

**Comment by ririko5834** [comment]
![image](https://user-images.githubusercontent.com/64729293/133934391-7fa10072-4c2e-4c92-b5f9-a257f059aec9.png)

**Comment by Stevanvincent** [comment]
secure: true

**Comment by ririko5834** [comment]
I have tried both 443 port with secure: true and 80 without secure

**Comment by ririko5834** [comment]
port 80 error:
![image](https://user-images.githubusercontent.com/64729293/133934647-320217ce-f782-4011-bd9c-dff2f3e414cb.png)

**Comment by ririko5834** [comment]
Must be the bot hosted on replit too?

**Comment by KagChi** [comment]
use port 443 and secure true
